### ISSUE TITLE
EWC workflow editor confused by "delay" parameter in action

### ISSUE THREAD

**Issue by blourdel** [StackStorm/ewc#13]
Hello,

When editing a workflow containing an action  with the "delay" parameter. As simple as :  
```yaml
  run_vm:
    action: core.noop
    delay: 30
    next:
      - when: <% succeeded() %>
        do: stop_vm
      - when: <% failed() %>
        do: fail_action
```
An error message is appearing on the UI. See attached.
This does not prevent to save the workflow though.

![delay](https://user-images.githubusercontent.com/22958735/66922055-94f4b780-f026-11e9-9829-81ca162e5b62.png)
.

ubuntu@ubuntu:~$ st2 --version
st2 3.1.0, on Python 2.7.12
